name: vibelit
description: VibeLit Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  shared_preferences:
  synchronized:
  flutter_bloc: ^5.0.0
  rxdart: ^0.23.1
  fluttertoast: ^6.0.0
  cupertino_icons: ^1.0.2
  path_provider: ^1.6.18
  dio: ^3.0.10
  weather_icons: ^2.0.2
  geolocator: ^5.3.2+2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 400
